import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

// import { Grid as GridComponent } from "../src/components/Grid";
// import { Grid } from "../src/grid";

// const GridTest: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <GridComponent grid={new Grid(5, 5)} />
//       </main>
//     </div>
//   );
// };

// export default GridTest;

const GridTest: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <GridComponent grid={new Grid(5, 5)} /> */}
      </main>
    </div>
  );
};

export default GridTest;
