import type { NextPage } from "next";
import Head from "next/head";

import stylesCss from "../styles/Home.module.css";
import { Grid2d } from "../src/components/Grid2d";
import { Grid3d } from "../src/components/Grid3d";
import { PrimMaze, primMazeToGrid } from "../src/primMaze";
import { useEffect, useMemo, useState } from "react";
import { GridTraversalManager, Orientation } from "../src/gridTraversalManager";
import { Grid } from "../src/grid";
import { randomInRange } from "../src/util/randomInRange";
import { Box } from "../src/components/WeirdLayoutStuffIllProbablyDeleteLater/Box";
import {
  Layout,
  Column,
} from "../src/components/WeirdLayoutStuffIllProbablyDeleteLater/Layout";

const GRID_SIZE = 5;

function findEmptyRoom(grid: Grid) {
  while (true) {
    const row = randomInRange(0, grid.height - 1);
    const col = randomInRange(0, grid.width - 1);
    const cell = grid.getCell(row, col);
    if (!cell.hasPropertyOfType("wall")) {
      return { row, col };
    }
  }
}

// The actual page

const GridTest: NextPage = () => {
  const [maze, setMaze] = useState<PrimMaze | null>(null);
  const [gridManager, setGridManager] = useState<GridTraversalManager | null>(
    null
  );

  useEffect(() => {
    setMaze(new PrimMaze(GRID_SIZE, GRID_SIZE));
  }, []);

  const grid = useMemo(() => {
    if (maze) {
      return primMazeToGrid(maze);
    }
    return null;
  }, [maze]);

  useEffect(() => {
    if (grid) {
      const { row, col } = findEmptyRoom(grid);
      const manager = new GridTraversalManager(grid, row, col);

      window.addEventListener("keyup", manager.listen);
      setGridManager(manager);

      return () => {
        window.removeEventListener("keyup", manager.listen);
      };
    }
  }, [grid]);

  const handleClick = () => {
    setMaze(new PrimMaze(GRID_SIZE, GRID_SIZE));
  };

  return (
    <div className={stylesCss.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={stylesCss.main}>
        {grid && gridManager && (
          <Layout columns={2}>
            <Column>
              <Box>
                <Grid3d />
              </Box>
            </Column>
            <Column>
              <Box>
                <Grid2d grid={grid} cellSize={15} />
              </Box>
            </Column>
          </Layout>
        )}
        <button onClick={handleClick}>generate new maze</button>
      </main>
    </div>
  );
};

export default GridTest;
